name: Frontend Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'components/**'
      - 'contexts/**'
      - 'hooks/**'
      - 'lib/**'
      - 'services/**'
      - 'types/**'
      - 'package.json'
      - 'package-lock.json'
      - 'jest.config.js'
      - 'jest.setup.js'
      - '.github/workflows/frontend-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'components/**'
      - 'contexts/**'
      - 'hooks/**'
      - 'lib/**'
      - 'services/**'
      - 'types/**'
      - 'package.json'
      - 'package-lock.json'
      - 'jest.config.js'
      - 'jest.setup.js'
      - '.github/workflows/frontend-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint
    
    - name: Run tests
      run: npm test
